[project]
name = "price-trigger"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.price-oracle]
path = "contracts/price-oracle.clar"
depends_on = []

[contracts.trigger-manager]
path = "contracts/trigger-manager.clar"
depends_on = ["price-oracle"]

[contracts.price-listener]
path = "contracts/price-listener.clar"
depends_on = ["price-oracle", "trigger-manager"]

[contracts.trigger-execution]
path = "contracts/trigger-execution.clar"
depends_on = ["price-listener", "trigger-manager"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
